# Generated by Django 3.1.5 on 2021-01-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='sort',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='machine',
            name='building',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='machine',
            name='machineid',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='machine',
            name='sort',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.IntegerField(default=None),
        ),
    ]
