# Generated by Django 3.1.5 on 2021-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0002_auto_20210124_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='NQT',
            field=models.TextField(default=None),
        ),
    ]
