# Generated by Django 3.1.8 on 2021-06-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dakauser',
            name='enable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dakauser',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dakauser',
            name='user',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
