# Generated by Django 3.1.7 on 2021-04-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eduadmin_id',
            field=models.CharField(db_index=True, default=None, max_length=10),
            preserve_default=False,
        ),
    ]
