# Generated by Django 3.1.8 on 2021-05-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_eduadmin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_id',
            field=models.CharField(db_index=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='eduadmin_id',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
