# Generated by Django 3.1.8 on 2021-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210514_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('token', models.UUIDField(db_index=True)),
                ('vpn_ticket', models.TextField()),
                ('at_token', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('destroy_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='at_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vpn_ticket',
        ),
    ]
