# Generated by Django 3.1.8 on 2021-08-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210726_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='unionid',
        ),
        migrations.AddField(
            model_name='loginstate',
            name='session_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
